name: schedule Job

on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Midnight Workflow
        run: echo "Schedule for midnight 1 Oclock"
